name: groveman_analytics_mixpanel_example
description: Example app for groveman_analytics_mixpanel.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  groveman_analytics: ^0.1.0
  groveman_analytics_mixpanel:
    path: ../
  mixpanel_flutter: ^2.0.0

dev_dependencies:
  lint: ^2.8.0

flutter:
  uses-material-design: true
