name: groveman

repository:
  type: github
  origin: https://github.com/kmartins/groveman
  owner: kmartins
  name: groveman

packages:
  - packages/**

ignore:
  - "packages/**/example"

command:
  version:
    workspaceChangelog: false
    message: |
      build({package}): new version

      {new_package_versions}

scripts:
  format:package:
    description: "Run `dart format` in a specific package."
    run: melos exec -- dart format .
    packageFilters:
      scope: "groveman*"

  analyze:package:
    description: "Run `dart analyze` in a specific package."
    run: melos exec -- dart analyze .
    packageFilters:
      scope: "groveman*"

  pane:package:
    description: "Pub score for a specific package."
    run: melos exec -c 1 -- pana . --no-warning
    packageFilters:
      scope: "groveman*"
